# site settings
title: FIDELIS'
subtitle: PORTFOLIO
email: fidelisike081@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: ENUGU
state: ENUGU
country: NIGERIA
phone: (+234)9021508603

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Fideliyke
  LinkedIn: https://www.linkedin.com/in/edeh-fidelis
  Twitter: https://x.com/Fidel_iyk?t=tHDCmg-_279FovDFDv1knw&s=09
  Instagram: https://instagram.com/fid_elike?igshid=MmVlMjlkMTBhMg==
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
